name: get
on:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches:
      - main

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Download
      run: |
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://akilar.top/ -o akilar.top.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://fomal.cc/ -o fomal.cc.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://fe32.top/ -o fe32.top.webp
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://blog.anheyu.com/ -o blog.anheyu.com.webp
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://blog.zhheo.com/ -o blog.zhheo.com.webp
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://saop.cc/ -o saop.cc.webp
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://yisous.xyz/ -o yisous.xyz.webp
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://zfe.space/ -o zfe.space.webp
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://vercel.dreamakerr.cn/ -o vercel.dreamakerr.cn.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://zh-v2.d2l.ai/ -o zh-v2.d2l.ai.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://bilibili.com/ -o bilibili.com.jpg
        

        curl https://purge.jsdelivr.net/gh/Dreamakerr/ScreenShot@gh-pages/*.*
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: ./
