name: get
on:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches:
      - main

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Download
      run: |
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://akilar.top/ -o akilar.top.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://fomal.cc/ -o fomal.cc.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://fe32.top/ -o fe32.top.webp
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://blog.anheyu.com/ -o blog.anheyu.com.webp
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://blog.zhheo.com/ -o blog.zhheo.com.webp
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://saop.cc/ -o saop.cc.webp
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://yisous.xyz/ -o yisous.xyz.webp
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://zfe.space/ -o zfe.space.webp
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://dreamakerr.cn/ -o dreamakerr.cn.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://blog.lovelu.top/ -o blog.lovelu.top.webp
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://noionion.top/ -o noionion.top.webp
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://dusays.com/ -o dusays.com.webp
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://immmmm.com/ -o immmmm.com.webp
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://zh-v2.d2l.ai/ -o zh-v2.d2l.ai.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://bilibili.com/ -o bilibili.com.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://xuancx.top/ -o xuancx.top.webp
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://blog.qyliu.top/ -o blog.qyliu.top.webp
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://www.quenan.love/ -o www.quenan.love.webp
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://hexo.io/zh-cn/ -o hexo.io.webp
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://butterfly.js.org/ -o butterfly.js.org.webp
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://vercel.com/ -o vercel.com.webp
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://github.com/ -o github.com.webp
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://www.acwing.com/ -o www.acwing.com.webp
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://leetcode.cn/ -o leetcode.cn.webp
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://codeforces.com/ -o codeforces.com.webp
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://www.luogu.com.cn/ -o www.luogu.com.cn.webp
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://chat.openai.com/chat -o chat.openai.com.webp
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://www.csdn.net/ -o www.csdn.net.webp
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://www.iconfont.cn/ -o www.iconfont.cn.webp
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://pygments.org/demo/#try -o pygments.org.webp
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://app.diagrams.net/ -o app.diagrams.net.webp
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://imagestool.com/zh_CN/ -o imagestool.com.webp
        

        curl https://purge.jsdelivr.net/gh/Dreamakerr/ScreenShot@gh-pages/*.*
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: ./
